name: CI/CD Pipeline

on: 
    push: 
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Lint with flake8
              run: |
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            - name: Start services with Docker Compose
              run: docker compose up --build -d

            - name: Wait for services to be ready
              run: | 
                echo "Waiting for PostgreSQL to be ready ..."
                until docker compose exec db pg_isready -U user -d jobs_db; do
                  echo "Waiting for database ..."
                  sleep 1
                done
                echo "Database is ready!"
                echo "Waiting for Redis to be ready ..."
                until docker compose exec redis-cli ping; do
                  echo "Waiting for Redis ..."
                  sleep 1
                done
                echo "Redis is ready!"

            - name: Run tests
              env:
                DATABASE_URL: postgresql://user:password@localhost:5433/jobs_db
                REDIS_URL: redis://localhost:6379/
              run: |
                pytest
